version: "3.1"
services: 
  mysqlDB:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: tb_admin
      MYSQL_PASSWORD: YHZ_hg2ua
      MYSQL_DATABASE: thr33books
    volumes: 
      - mysql_data:/var/lib/mysql 
    restart: always

  thr33books:
    build: 
      context: .
    volumes: 
      - .:/home/node/app
    depends_on: 
      - mysqlDB
    ports: 
      - "8080:3000"
    command: "npm start"

volumes: 
  mysql_data: {}